---
version: '2'
# version: '3.2'
# extra_hosts:
#  - "service.localhost:172.16.123.1"

services:

  data:
    image: tianon/true
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./shared/data:/shared/data"
    - "./shared/logs:/shared/logs"
    - "./shared/conf.d:/shared/conf.d"


  # git subtree add --prefix services/src/redzilla https://github.com/muka/redzilla master --squash
  redzilla:
    image: opny/redzilla
    # image: redzilla:latest-alpine3.6
    container_name: redzilla
    networks:
    - fbp
    ports:
    - "3000:3000"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d

  goflow_draw:
    image: goflow-draw:latest-alpine3.6
    container_name: goflow-draw
    build:
      context: services/goflow-draw
      dockerfile: goflow-ui.alpine.dockerfile
    env_file:
    - "./services/goflow-draw/goflow-ui.alpine.env"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    networks:
    - fbp
    volumes:
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d
    ports:
    # - "80:80"
    # - "443:443"
    - "2015:2015"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"

  node_red:
    image: node-red:latest-alpine3.6
    container_name: node-red
    build:
      context: services/node-red-ui
      dockerfile: node-red-ui.alpine.dockerfile
    env_file:
    - "./services/node-red-ui/node-red-ui.alpine.env"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    networks:
    - fbp
    volumes:
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d
    ports:
    # - "80:80"
    # - "443:443"
    - "2015:2015"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"

  noflow_graph_server:
    image: noflo-graph-server:latest-alpine3.6
    container_name: noflo-graph-server
    build:
      context: services/noflo-server-graph
      dockerfile: noflo-server-graph.alpine.dockerfile
    env_file:
    - "./services/noflo-server-graph/noflo-server-graph.alpine.env"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    networks:
    - fbp
    volumes:
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d
    ports:
    # - "80:80"
    # - "443:443"
    - "2015:2015"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"

  # git subtree add --prefix services/msgflo-cpp/src https://github.com/msgflo-cpp/msgflo master --squash
  msgflo_cpp:
    image: msgflo-cpp:latest-alpine3.6
    container_name: msgflo-cpp
    build:
      context: services/msgflo-cpp
      dockerfile:  msgflo-cpp.alpine.dockerfile
    env_file:
    - "./services/msgflo-cpp/msgflo-cpp.alpine.env"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    networks:
    - fbp
    volumes:
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d
    ports:
    # - "80:80"
    # - "443:443"
    - "2015:2015"
    - "2025:2025"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"

  # git subtree add --prefix services/msgflo/src https://github.com/msgflo/msgflo master --squash
  msgflo:
    image: msgflo:latest-alpine3.6
    container_name: msgflo
    build:
      context: services/msgflo
      dockerfile: msgflo.alpine.dockerfile
    env_file:
    - "./services/msgflo/msgflo.alpine.env"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    networks:
    - fbp
    volumes:
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d
    ports:
    # - "80:80"
    # - "443:443"
    - "3015:3015"
    - "3025:3025"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"

volumes:
  data: 

