---
version: '2'
# version: '3.2'
# extra_hosts:
#  - "service.localhost:172.16.123.1"

services:

  data:
    image: tianon/true
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./shared/data:/shared/data"
    - "./shared/logs:/shared/logs"
    - "./shared/conf.d:/shared/conf.d"

  proxy:
    image: traefik
    # image: traefik:latest-alpine3.6
    command: --web --docker --docker.watch --docker.domain=localhost --logLevel=DEBUG --entryPoints="Name:http Address::80"
    networks:
    - fbp
    - webproxy
    ports:
    - "80:80"
    - "8080:8080"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./shared/conf.d/traefik/traefik.toml:/traefik.toml
    # - /dev/null:/traefik.toml
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d

  redzilla:
    image: opny/redzilla
    # image: redzilla:latest-alpine3.6
    container_name: redzilla
    networks:
    - fbp
    ports:
    - "3000:3000"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d
    labels:
    - "traefik.backend=redzilla"
    - "traefik.port=3000"
    - "traefik.frontend.entryPoints=http"

  goflow_draw:
    image: goflow-draw:latest-alpine3.6
    container_name: goflow-draw
    build:
      context: services/goflow-draw
      dockerfile: goflow-ui.alpine.dockerfile
    env_file:
    - "./services/goflow-draw/goflow-ui.alpine.env"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    networks:
    - fbp
    volumes:
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d
    ports:
    # - "80:80"
    # - "443:443"
    - "2015:2015"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    labels:
    - "traefik.backend=goflow-draw"
    - "traefik.port=2015"
    - "traefik.frontend.entryPoints=http"

  node_red:
    image: node-red:latest-alpine3.6
    container_name: node-red
    build:
      context: services/goflow-draw
      dockerfile: goflow-ui.alpine.dockerfile
    env_file:
    - "./services/goflow-draw/goflow-ui.alpine.env"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    networks:
    - fbp
    volumes:
    - data:/shared/data
    - data:/shared/logs
    - data:/shared/www
    - data:/shared/conf.d
    ports:
    # - "80:80"
    # - "443:443"
    - "2015:2015"
    extra_hosts:
    - "dockerhost:$DOCKERHOST"
    labels:
    - "traefik.backend=goflow-draw"
    - "traefik.port=2015"
    - "traefik.frontend.entryPoints=http"

networks:
  webproxy:
    driver: bridge
  fbp:
    driver: bridge

volumes:
  data: 

