sudo: required

language: npm

services:
  - docker

before_install:
  - docker build -t reg.rewasa.ch:5000/noflo-nodejs-graph .
  - docker run -d -p 3569:3569 reg.rewasa.ch:5000/noflo-nodejs-graph

script:
- bundle exec rake test